name: Build Debian package

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-24.04

    name: Build Debian package
    steps:
      - uses: actions/checkout@v4
      - name: Update apt cache
        run: |
          sudo apt-get update
      - name: Install Poetry
        run: |
          pipx install poetry~=2.1.3
          python --version; python -m pip --version; poetry --version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "poetry"
      - name: Setup project with Poetry
        run: poetry install --no-interaction
      - name: Prepare to build a Debian source package
        run: |
          sudo apt-get -y install build-essential debhelper dh-make rename

      - name: Build a Debian package
        run: |
          poetry run poe build_deb

      - name: Archive the built Debian package
        uses: actions/upload-artifact@v4
        with:
          name: smartmeter-datacollector-deb
          path: deb_dist/*.deb

      - name: Archive the additional Debian package files
        uses: actions/upload-artifact@v4
        with:
          name: smartmeter-datacollector-packagefiles
          path: |
            deb_dist/*.buildinfo
            deb_dist/*.changes
            deb_dist/*.tar.*

      - name: Get the tag name
        id: tagName
        if: startsWith(github.ref, 'refs/tags')
        uses: olegtarasov/get-tag@v2.1.4

      - name: Create a new release
        if: startsWith(github.ref, 'refs/tags')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: deb_dist/*.deb
          draft: true
          name: Smart Meter Data Collector ${{ steps.tagName.outputs.tag }}
          omitBody: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
